### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by pkieltyka** [pressly/chi#49]
Below are remaining things I'd like to complete for v2 release:
- [x] Finalize chi.Router interface
- [x] Syntax: chi.URLParam(r, "id")
- [x] Example of Handler unit tests in v2
- [x] Include RoutePattern on the request context, which is the pattern string that matches a request, helpful for instrumentation middlewares (#45)
- [x] Example with handlers on a struct
- [x] Finalize render.Presenter (#47)
- [x] Godoc
- [x] Document examples (render, etc.)
- [x] Updated benchmarks
- [ ] Real-life example with chi+config+Makefile+upper+tests+templates+http2

**Comment by november-eleven** [comment]
Hello,

First of all, **thank you** for this amazing router: it's the most elegant and minimalist solution I've found for the moment.

I have a question however for the v2 release of chi, would it be possible to link a `LogHandler` (or `LogHook`) interface with the `Logger` middleware ?
Why I'm asking this ? Because nowadays if you prefer to use **logrus** with **chi** _(for example)_, you have to copy/paste _(or fork)_ the `Logger` middleware in order to override the `printRequest` function.

Or, another solution would be to expose a `Metrics` middleware, which can forward these metrics to a `MetricsHandler` interface: for exemple, a Logger, a NSQ Producer or a InfluxDB database.

Depending of your preference, I can submit a pull request in the `v2` branch.

**Comment by pkieltyka** [comment]
@november-eleven thanks man, that was the goal :)

ahh yes.. the logger interface, I agree this would be a good addition and if you want to take a stab at a prototype+PR, go for it. The simpler the better. I'll add it to the v2 roadmap as well.

**Comment by pkieltyka** [comment]
@november-eleven btw, I don't know if you've seen but I added a pretty sweet Logger interface and logging example for structure logging last week.

**Comment by november-eleven** [comment]
@pkieltyka Yeah, you've done a terrific job, as always :smile:

**Comment by pkieltyka** [comment]
https://github.com/pressly/chi/releases/tag/v2.0.0
